# Form implementation generated from reading ui file 'gui_main.ui'
# Created by: PyQt6 UI code generator 6.6.1

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.generate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.generate.setGeometry(QtCore.QRect(690, 10, 101, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        self.generate.setFont(font)
        self.generate.setStyleSheet("background-color:rgb(1, 127, 173);\n"
"color: white")
        self.generate.setDefault(False)
        self.generate.setFlat(False)
        self.generate.setObjectName("generate")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 90, 781, 371))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.DataTable = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.DataTable.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.DataTable.setContentsMargins(10, 5, 10, 0)
        self.DataTable.setHorizontalSpacing(20)
        self.DataTable.setVerticalSpacing(10)
        self.DataTable.setObjectName("DataTable")
        self.line = QtWidgets.QFrame(parent=self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.DataTable.addWidget(self.line, 0, 2, 1, 1)
        self.datasys = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        self.datasys.setFont(font)
        self.datasys.setToolTipDuration(0)
        self.datasys.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.datasys.setStyleSheet("")
        self.datasys.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.datasys.setScaledContents(False)
        self.datasys.setWordWrap(False)
        self.datasys.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.datasys.setObjectName("datasys")
        self.DataTable.addWidget(self.datasys, 1, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.database = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        self.database.setFont(font)
        self.database.setToolTipDuration(0)
        self.database.setWhatsThis("")
        self.database.setObjectName("database")
        self.DataTable.addWidget(self.database, 1, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color:white;")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setTextElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(125)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.DataTable.addWidget(self.tableWidget, 0, 1, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("background-color:white;")
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(125)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.DataTable.addWidget(self.tableWidget_2, 0, 3, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(550, 670, 241, 26))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.release_page = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        self.release_page.setFont(font)
        self.release_page.setStyleSheet("")
        self.release_page.setObjectName("release_page")
        self.horizontalLayout.addWidget(self.release_page)
        self.user_manual = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        self.user_manual.setFont(font)
        self.user_manual.setStyleSheet("background-color:rgb(232, 155, 0)")
        self.user_manual.setObjectName("user_manual")
        self.horizontalLayout.addWidget(self.user_manual)
        self.version_num = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.version_num.setFont(font)
        self.version_num.setObjectName("version_num")
        self.horizontalLayout.addWidget(self.version_num, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, 469, 781, 191))
        self.frame.setStyleSheet("border-style: outset;\n"
"border-width:2px;\n"
"background-color:rgb(210, 210, 210)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridFrame_2 = QtWidgets.QFrame(parent=self.frame)
        self.gridFrame_2.setGeometry(QtCore.QRect(10, 11, 361, 171))
        self.gridFrame_2.setStyleSheet("border-width:1px;\n"
"background-color:rgb(230, 230, 230)")
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.gridFrame_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-width:0px;")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.gridFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color:white;\n"
"border-width:0px;")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 5, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label = QtWidgets.QLabel(parent=self.gridFrame_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("border-width:0px")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.gridFrame_2)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-width:0px;\n"
"background-color:white;")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.gridFrame_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-width:0px;\n"
"background-color:white;")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 3, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.gridFrame_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color:white;\n"
"border-width:0px;")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 4, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3 = QtWidgets.QLabel(parent=self.gridFrame_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-width:0px;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridFrame_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-width:0px;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 2, 2, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4 = QtWidgets.QLabel(parent=self.gridFrame_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-width:0px;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.gridFrame_2)
        self.lineEdit_9.setStyleSheet("border-width:0px;\n"
"background-color:white;")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 6, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.gridFrame_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border-width:0px;")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_2.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.label_5.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_9.raise_()
        self.label_11.raise_()
        self.gridFrame_3 = QtWidgets.QFrame(parent=self.frame)
        self.gridFrame_3.setGeometry(QtCore.QRect(410, 11, 361, 171))
        self.gridFrame_3.setStyleSheet("border-width:1px;\n"
"background-color:rgb(230, 230, 230)")
        self.gridFrame_3.setObjectName("gridFrame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame_3)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(parent=self.gridFrame_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border-width:0px;")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.gridFrame_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border-width:0px;")
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 8, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.gridFrame_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border-width:0px;")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.gridFrame_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border-width:0px;")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.gridFrame_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border-width:0px")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.gridFrame_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border-width:0px;")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.gridFrame_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("border-width:0px;\n"
"background-color:white;")
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 4, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.gridFrame_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("border-width:0px;\n"
"background-color:white;")
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 5, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.gridFrame_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("background-color:white;\n"
"border-width:0px;")
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 6, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.gridFrame_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color:white;\n"
"border-width:0px;")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 7, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.gridFrame_3)
        self.lineEdit_10.setStyleSheet("border-width:0px;\n"
"background-color:white;")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 8, 1, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(20, 50, 661, 31))
        self.splitter_3.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.sys_name = QtWidgets.QLabel(parent=self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.sys_name.setFont(font)
        self.sys_name.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.sys_name.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.sys_name.setObjectName("sys_name")
        self.file_sys = QtWidgets.QTextBrowser(parent=self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.file_sys.setFont(font)
        self.file_sys.setMouseTracking(True)
        self.file_sys.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.file_sys.setReadOnly(True)
        self.file_sys.setObjectName("file_sys")
        self.open_sys = QtWidgets.QPushButton(parent=self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.open_sys.setFont(font)
        self.open_sys.setObjectName("open_sys")
        self.splitter_2 = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(20, 10, 661, 31))
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_2.setHandleWidth(5)
        self.splitter_2.setObjectName("splitter_2")
        self.base_name = QtWidgets.QLabel(parent=self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.base_name.setFont(font)
        self.base_name.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.base_name.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.base_name.setObjectName("base_name")
        self.file_base = QtWidgets.QTextBrowser(parent=self.splitter_2)
        self.file_base.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.file_base.setFont(font)
        self.file_base.setMouseTracking(True)
        self.file_base.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.file_base.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhMultiLine)
        self.file_base.setObjectName("file_base")
        self.open_base = QtWidgets.QPushButton(parent=self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.open_base.setFont(font)
        self.open_base.setStyleSheet("border-image: url(:/newPrefix/computer-folder-search-icon.png);")
        self.open_base.setObjectName("open_base")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Profile Comparator"))
        self.generate.setText(_translate("MainWindow", "Generate"))
        self.datasys.setText(_translate("MainWindow", "System Load Profile"))
        self.database.setText(_translate("MainWindow", "Baseline Load Profile"))
        self.release_page.setText(_translate("MainWindow", "Release Page"))
        self.user_manual.setText(_translate("MainWindow", "User Manual"))
        self.version_num.setText(_translate("MainWindow", "Ver. 1.1"))
        self.label_5.setText(_translate("MainWindow", "Time of Max Heating (Hr)"))
        self.label.setText(_translate("MainWindow", "Time of Max Cooling (Hr)"))
        self.label_3.setText(_translate("MainWindow", "Max System Cooling (kW)"))
        self.label_2.setText(_translate("MainWindow", "System Load Profile Summary"))
        self.label_4.setText(_translate("MainWindow", "Min System Heating (kW)"))
        self.label_11.setText(_translate("MainWindow", "Hours Recorded (Hr)"))
        self.label_7.setText(_translate("MainWindow", "Baseline Load (kW)"))
        self.label_12.setText(_translate("MainWindow", "Hour Deficit/Gain (±kW/±%)"))
        self.label_8.setText(_translate("MainWindow", "Load Deficit/Gain (±kW/±%)"))
        self.label_6.setText(_translate("MainWindow", "System Load (kW)"))
        self.label_9.setText(_translate("MainWindow", "Time Selected (Hr)"))
        self.label_10.setText(_translate("MainWindow", "Selected Data"))
        self.sys_name.setText(_translate("MainWindow", "System Load Profile  "))
        self.open_sys.setText(_translate("MainWindow", "Open"))
        self.base_name.setText(_translate("MainWindow", "Baseline Load Profile"))
        self.open_base.setText(_translate("MainWindow", "Open"))
